# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'windows.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QPushButton, QSizePolicy, QTextBrowser, QTextEdit,
    QWidget)

class Ui_STAT(object):
    def setupUi(self, STAT):
        if not STAT.objectName():
            STAT.setObjectName(u"STAT")
        STAT.resize(852, 609)
        STAT.setSizeGripEnabled(False)
        self.Output_lable = QLabel(STAT)
        self.Output_lable.setObjectName(u"Output_lable")
        self.Output_lable.setGeometry(QRect(490, 310, 91, 16))
        self.Forward = QPushButton(STAT)
        self.Forward.setObjectName(u"Forward")
        self.Forward.setGeometry(QRect(730, 580, 75, 24))
        self.Output_text = QTextEdit(STAT)
        self.Output_text.setObjectName(u"Output_text")
        self.Output_text.setGeometry(QRect(490, 330, 361, 231))
        self.Input_text = QTextEdit(STAT)
        self.Input_text.setObjectName(u"Input_text")
        self.Input_text.setGeometry(QRect(490, 40, 361, 231))
        self.Input_label = QLabel(STAT)
        self.Input_label.setObjectName(u"Input_label")
        self.Input_label.setGeometry(QRect(490, 20, 81, 16))
        self.line = QFrame(STAT)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(460, 0, 20, 611))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(STAT)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(470, 300, 381, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.RollBack = QPushButton(STAT)
        self.RollBack.setObjectName(u"RollBack")
        self.RollBack.setGeometry(QRect(530, 580, 75, 24))
        self.line_3 = QFrame(STAT)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(130, 0, 20, 611))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(STAT)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(140, 330, 331, 20))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.History_label = QLabel(STAT)
        self.History_label.setObjectName(u"History_label")
        self.History_label.setGeometry(QRect(170, 20, 54, 16))
        self.Analysis_label = QLabel(STAT)
        self.Analysis_label.setObjectName(u"Analysis_label")
        self.Analysis_label.setGeometry(QRect(170, 340, 54, 16))
        self.Options = QLabel(STAT)
        self.Options.setObjectName(u"Options")
        self.Options.setGeometry(QRect(40, 20, 54, 16))
        self.History_text = QTextBrowser(STAT)
        self.History_text.setObjectName(u"History_text")
        self.History_text.setGeometry(QRect(160, 50, 291, 271))
        self.Analysis_text = QTextBrowser(STAT)
        self.Analysis_text.setObjectName(u"Analysis_text")
        self.Analysis_text.setGeometry(QRect(160, 370, 291, 221))
        self.Caesar = QPushButton(STAT)
        self.Caesar.setObjectName(u"Caesar")
        self.Caesar.setGeometry(QRect(30, 60, 75, 24))
        self.Affine = QPushButton(STAT)
        self.Affine.setObjectName(u"Affine")
        self.Affine.setGeometry(QRect(30, 110, 75, 24))
        self.Playfair = QPushButton(STAT)
        self.Playfair.setObjectName(u"Playfair")
        self.Playfair.setGeometry(QRect(30, 160, 75, 24))
        self.Atbash = QPushButton(STAT)
        self.Atbash.setObjectName(u"Atbash")
        self.Atbash.setGeometry(QRect(30, 210, 75, 24))
        self.Replace = QPushButton(STAT)
        self.Replace.setObjectName(u"Replace")
        self.Replace.setGeometry(QRect(30, 260, 75, 24))
        self.FindThe = QPushButton(STAT)
        self.FindThe.setObjectName(u"FindThe")
        self.FindThe.setGeometry(QRect(30, 500, 75, 24))
        self.FineChar = QPushButton(STAT)
        self.FineChar.setObjectName(u"FineChar")
        self.FineChar.setGeometry(QRect(30, 550, 75, 24))
        self.isMonoalphabetic = QPushButton(STAT)
        self.isMonoalphabetic.setObjectName(u"isMonoalphabetic")
        self.isMonoalphabetic.setGeometry(QRect(30, 450, 75, 24))
        self.CaesarKey = QPushButton(STAT)
        self.CaesarKey.setObjectName(u"CaesarKey")
        self.CaesarKey.setGeometry(QRect(30, 400, 80, 24))
        self.Frequency = QPushButton(STAT)
        self.Frequency.setObjectName(u"Frequency")
        self.Frequency.setGeometry(QRect(30, 350, 75, 24))
        self.LOAD = QPushButton(STAT)
        self.LOAD.setObjectName(u"LOAD")
        self.LOAD.setGeometry(QRect(630, 280, 75, 24))
        self.Tips = QPushButton(STAT)
        self.Tips.setObjectName(u"Tips")
        self.Tips.setGeometry(QRect(630, 580, 75, 24))

        self.retranslateUi(STAT)

        QMetaObject.connectSlotsByName(STAT)
    # setupUi

    def retranslateUi(self, STAT):
        STAT.setWindowTitle(QCoreApplication.translate("STAT", u"\u5355\u8868\u4ee3\u6362\u5de5\u5177", None))
        self.Output_lable.setText(QCoreApplication.translate("STAT", u"Output String", None))
#if QT_CONFIG(tooltip)
        self.Forward.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u5728\u4f7f\u7528\u4e0a\u4e00\u6b65\u540e\uff0c\u53ef\u4ee5\u7528\u4e0b\u4e00\u6b65\u64cd\u4f5c\u56de\u53bb</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.Forward.setWhatsThis(QCoreApplication.translate("STAT", u"<html><head/><body><p>123</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.Forward.setText(QCoreApplication.translate("STAT", u"\u4e0b\u4e00\u6b65", None))
        self.Output_text.setPlaceholderText(QCoreApplication.translate("STAT", u"output", None))
        self.Input_text.setPlaceholderText(QCoreApplication.translate("STAT", u"input", None))
        self.Input_label.setText(QCoreApplication.translate("STAT", u"Input String", None))
#if QT_CONFIG(tooltip)
        self.RollBack.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u8fd4\u56de\u4e0a\u4e00\u6b65</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.RollBack.setText(QCoreApplication.translate("STAT", u"\u4e0a\u4e00\u6b65", None))
        self.History_label.setText(QCoreApplication.translate("STAT", u"History", None))
        self.Analysis_label.setText(QCoreApplication.translate("STAT", u"Analysis", None))
        self.Options.setText(QCoreApplication.translate("STAT", u"Options", None))
        self.Caesar.setText(QCoreApplication.translate("STAT", u"\u51ef\u6492\u5bc6\u7801", None))
        self.Affine.setText(QCoreApplication.translate("STAT", u"\u4eff\u5c04\u5bc6\u7801", None))
        self.Playfair.setText(QCoreApplication.translate("STAT", u"Playfair\u5bc6\u7801", None))
        self.Atbash.setText(QCoreApplication.translate("STAT", u"Atbash\u5bc6\u7801", None))
#if QT_CONFIG(tooltip)
        self.Replace.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u53ef\u8fdb\u884c\u5355\u5b57\u7b26\u6216\u591a\u5b57\u7b26\u4ee3\u6362</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.Replace.setText(QCoreApplication.translate("STAT", u"\u5b57\u7b26\u4ee3\u6362", None))
#if QT_CONFIG(tooltip)
        self.FindThe.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u63a8\u8350\u4e00\u5f00\u59cb\u4f7f\u7528\uff0c\u7528\u4e8e\u5bfb\u627e\u6587\u672c\u4e2d\u6700\u53ef\u80fd\u4e3athe\u7684\u4e09\u4e2a\u5b57\u6bcd</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.FindThe.setText(QCoreApplication.translate("STAT", u"\u9884\u6d4bthe", None))
#if QT_CONFIG(tooltip)
        self.FineChar.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u9884\u6d4b\u4e0b\u4e00\u4e2a\u9891\u7387\u6700\u9ad8\u7684\u5b57\u7b26\u7684\u53ef\u80fd\u503c</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.FineChar.setText(QCoreApplication.translate("STAT", u"\u9884\u6d4b\u5b57\u7b26", None))
#if QT_CONFIG(tooltip)
        self.isMonoalphabetic.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u5224\u65ad\u662f\u5426\u4e3a\u5355\u8868\u4ee3\u6362</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.isMonoalphabetic.setWhatsThis(QCoreApplication.translate("STAT", u"\u5224\u65ad\u662f\u5426\u4e3a\u5355\u8868\u4ee3\u6362", None))
#endif // QT_CONFIG(whatsthis)
        self.isMonoalphabetic.setText(QCoreApplication.translate("STAT", u"\u5355\u8868\u4ee3\u6362\uff1f", None))
#if QT_CONFIG(tooltip)
        self.CaesarKey.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u6839\u636e\u5355\u5b57\u6bcd\u9891\u7387\u5206\u6790\uff0c\u731c\u6d4b\u51ef\u6492\u5bc6\u7801\u5bc6\u94a5</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.CaesarKey.setText(QCoreApplication.translate("STAT", u"\u51ef\u6492\u5bc6\u94a5\u5206\u6790", None))
#if QT_CONFIG(tooltip)
        self.Frequency.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u8fd4\u56deinput\u5185\u5bb9\u7684n-gram\u9891\u7387\uff08n = 1,2,3\uff09</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.Frequency.setText(QCoreApplication.translate("STAT", u"\u9891\u7387\u5206\u6790", None))
#if QT_CONFIG(tooltip)
        self.LOAD.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u4f7f\u7528\u8fc7\u7a0b\u4e2d\u8c28\u614e\u70b9\u51fb\uff0c\u8fd9\u4f1a\u5bfc\u81f4\u4e2d\u95f4\u8fc7\u7a0b\u88ab\u6e05\u7a7a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.LOAD.setText(QCoreApplication.translate("STAT", u"LOAD", None))
#if QT_CONFIG(tooltip)
        self.Tips.setToolTip(QCoreApplication.translate("STAT", u"<html><head/><body><p>\u70b9\u6211\uff0c\u770b\u63d0\u793a\uff01\uff01</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.Tips.setText(QCoreApplication.translate("STAT", u"Tips", None))
    # retranslateUi

